input {
  file {
    path => "C:/elastic_stack/logs/activity.log"
    start_position => "beginning"
    sincedb_path => "NUL"
  }
}

filter {
  json {
    source => "message"
  }
}

output {
  elasticsearch {
    hosts => ["localhost:9200"]
    index => "cyber-logs"
  }

  stdout { codec => rubydebug }
}
